draw_config:
  key_w: 60
  key_h: 56
  split_gap: 30.0
  combo_w: 28
  combo_h: 26
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: auto
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0.0
    rel_y: 4.0
    rel_w: 12.0
    rel_h: 12.0
    rx: 4.0
    ry: 4.0
  svg_extra_style: |
    svg.keymap {
      font-family: Ubuntu Mono, Inconsolata, Liberation Mono, Menlo, monospace;
      font-size: 14px;
      font-weight: 600;
      text-rendering: optimizeLegibility;
    }

    // borrowed from https://github.com/SethMilliken/zmk-config/blob/main/keymap_drawer.config.yaml
    .sym_sub_text.tap {
      translate: -5px 2px;
      font-size: 20px;
    }
    .sym_sub_text.shifted {
      translate: 10px 13px;
      font-size: 10px;
      opacity: 1.0;
    }
    .combo.sym_sub_text.tap {
      translate: -1px 1px;
    }
    .combo.sym_sub_text.shifted {
      translate: 7px 5px;
      font-size: 10px;
      opacity: 1.0;
    }

    /* Variant for symbol next to symbol */
    .sym_by_sym.tap {
      translate: -6px 0px;
    }
    .sym_by_sym.shifted {
      translate: 10px 16px;
      opacity: 1.0;
    }

    .combo.sym_by_sym.tap {
      translate: -35px 0px;
    }
    .combo.sym_by_sym.shifted {
      translate: 35px 20px;
      opacity: 1.0;
    }

    .combo.sym_by_sym.hold {
      visibility: hidden;
    }

  footer_text: 'Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>'
  shrink_wide_legends: 5
  style_layer_activators: true
  glyph_tap_size: 18
  glyph_hold_size: 15
  glyph_shifted_size: 15
  glyphs: {}
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map:
    '&studio_unlock':
      shifted: Studio
      tap: $$mdi:lock-open-outline$$
    '&caps_word':
      tap: Word
      shifted: $$mdi:apple-keyboard-caps$$
    
    '&td_sys_reset':
      shifted: Reset
      tap: $$mdi:flash-alert$$ 
      hold: tap 3x
    '&td_bt_clr':
      tap: $$mdi:bluetooth-settings$$
      shifted: $$mdi:close-thick$$
      hold: tap 3x
      type: sym_by_sym
    '&td_bootloader':
      shifted: $$mdi:usb-flash-drive$$
      tap: $$mdi:flash$$
      hold: tap 3x
      type: sym_by_sym
    '&td_tog_colemak':
      shifted: $$mdi:toggle-switch-outline$$
      tap: Colemak-DH
      hold: tap 3x
    '&td_tog_but':
      shifted: $$mdi:toggle-switch-outline$$
      tap: BUT
      hold: tap 3x

    '&mt_sk LSHFT LSHFT':
      tap: $$mdi:apple-keyboard-shift$$
      shifted: $$mdi:numeric-1$$
      hold: $$mdi:apple-keyboard-shift$$
      type: sym_by_sym
    '&mt_kt LSHFT LSHFT':
      tap: $$mdi:apple-keyboard-shift$$
      shifted: $$mdi:toggle-switch-outline$$
      hold: $$mdi:apple-keyboard-shift$$
      type: sym_by_sym
    '&mo_sk NUM_NAV LSHFT':
      tap: $$mdi:apple-keyboard-shift$$
      shifted: $$mdi:numeric-1$$
      hold: num_nav
      type: sym_by_sym

    "&mmv MOVE_UP":
      tap: $$mdi:mouse$$
      shifted: $$mdi:arrow-up-bold$$
      type: sym_by_sym
    "&mmv MOVE_LEFT":
      tap: $$mdi:mouse$$
      shifted: $$mdi:arrow-left-bold$$
      type: sym_by_sym
    "&mmv MOVE_DOWN":
      tap: $$mdi:mouse$$
      shifted: $$mdi:arrow-down-bold$$
      type: sym_by_sym
    "&mmv MOVE_RIGHT":
      tap: $$mdi:mouse$$
      shifted: $$mdi:arrow-right-bold$$
      type: sym_by_sym

    "&mkp MB1":
      tap: $$mdi:mouse-left-click-outline$$
    "&mkp MB2":
      tap: $$mdi:mouse-right-click-outline$$
    "&mkp MB3":
      shifted: $$mdi:mouse$$
      tap: MB3
    "&mkp MB4":
      shifted: $$mdi:mouse$$
      tap: MB4
    "&mkp MB5":
      shifted: $$mdi:mouse$$
      tap: MB5

    "&msc SCRL_UP":
      tap: $$mdi:mouse-scroll-wheel$$
      shifted: $$mdi:transfer-up$$
      type: sym_by_sym
    "&msc SCRL_DOWN":
      tap: $$mdi:mouse-scroll-wheel$$
      shifted: $$mdi:transfer-down$$
      type: sym_by_sym
    "&msc SCRL_LEFT":
      tap: $$mdi:mouse-scroll-wheel$$
      shifted: $$mdi:transfer-left$$
      type: sym_by_sym
    "&msc SCRL_RIGHT":
      tap: $$mdi:mouse-scroll-wheel$$
      shifted: $$mdi:transfer-right$$
      type: sym_by_sym

    '&rgb_ug RGB_TOG':
      tap: $$mdi:toggle-switch-outline$$
      hold: $$mdi:led-on$$
      shifted: $$mdi:led-off$$
      type: toggle
    '&rgb_ug RGB_BRI':
      tap:     $$mdi:led-variant-outline$$
      shifted: $$mdi:white-balance-sunny$$
      hold:    $$mdi:arrow-up$$
      type:    sym_by_sym
    '&rgb_ug RGB_SAI':
      tap:     $$mdi:led-variant-outline$$
      shifted: $$mdi:eyedropper$$
      hold:    $$mdi:arrow-up$$
      type:    sym_by_sym
    '&rgb_ug RGB_HUI':
      tap:     $$mdi:led-variant-outline$$
      shifted: $$mdi:palette$$
      hold:    $$mdi:arrow-up$$
      type:    sym_by_sym
    '&rgb_ug RGB_BRD':
      tap:     $$mdi:led-variant-outline$$
      shifted: $$mdi:white-balance-sunny$$
      hold:    $$mdi:arrow-down$$
      type:    sym_by_sym
    '&rgb_ug RGB_SAD':
      tap:     $$mdi:led-variant-outline$$
      shifted: $$mdi:eyedropper$$
      hold:    $$mdi:arrow-down$$
      type:    sym_by_sym
    '&rgb_ug RGB_HUD':
      tap:     $$mdi:led-variant-outline$$
      shifted: $$mdi:palette$$
      hold:    $$mdi:arrow-down$$
      type:    sym_by_sym

    '&rgb_ug RGB_EFF':
      tap:     $$mdi:led-variant-outline$$
      shifted: $$mdi:animation-play$$
      hold:    $$mdi:arrow-up$$
      type:    sym_by_sym
    '&rgb_ug RGB_EFR':
      tap:     $$mdi:led-variant-outline$$
      shifted: $$mdi:animation-play$$
      hold:    $$mdi:arrow-down$$
      type:    sym_by_sym
    
    '&rgb_ug COLOR_RED':
      tap:     $$mdi:led-variant-outline$$
      shifted: $$mdi:palette$$
      hold:    Red
      type:    sym_by_sym
    '&rgb_ug COLOR_GREEN':
      tap:     $$mdi:led-variant-outline$$
      shifted: $$mdi:palette$$
      hold:    Green
      type:    sym_by_sym
    '&rgb_ug COLOR_BLUE':
      tap:     $$mdi:led-variant-outline$$
      shifted: $$mdi:palette$$
      hold:    Blue
      type:    sym_by_sym
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ▽
    type: trans
  layer_legend_map: {}
  mark_alternate_layer_activators: true
  modifier_fn_map:
    left_ctrl: Ctrl
    right_ctrl: Ctrl
    left_shift: Shft
    right_shift: Shft
    left_alt: Alt
    right_alt: AltGr
    left_gui: GUI
    right_gui: GUI
    keycode_combiner: '{mods}+{key}'
    mod_combiner: '{mod_1}+{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  zmk_remove_keycode_prefix:
  - 'DE_'
  zmk_keycode_map:
    BSPC:
      type: backspace
      tap: $$mdi:backspace-outline$$
    RET:
      type: enter
      tap: $$mdi:keyboard-return$$
    SPC:
      type: space
      tap: $$mdi:keyboard-space$$
    SPACE:
      type: space
      tap: $$mdi:keyboard-space$$
    TAB:
      type: tab
      tap: $$mdi:keyboard-tab$$
    CAPS: $$mdi:apple-keyboard-caps$$
    DEL: $$mdi:backspace-reverse-outline$$
    GLOBE:
      tap: $$mdi:web$$
      shifted: $$mdi:apple$$
      type: sym_by_sym

    LCTRL: Ctrl
    LALT: Alt
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LGUI: GUI
    RCTRL: Ctrl
    RALT: AltGr
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RGUI: GUI

    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$

    C_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$
    C_PP: $$mdi:play-pause$$

    BT_CLR: $$mdi:bluetooth-off$$
    BT_SEL: $$mdi:bluetooth-connect$$
    BT_DISC: $$mdi:bluetooth-off$$

    PG_UP: 
      tap: Page
      hold: $$mdi:arrow-up$$
    PG_DN:
      tap: Page
      hold: $$mdi:arrow-down$$

    UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$

    ESC: Esc
    HOME: Home
    END: End

    A_UMLAUT: 'Ä'
    O_UMLAUT: 'Ö'
    U_UMLAUT: 'Ü'
    SHARP_S: 'ß'
    SZ: 'ß'

    MUTE_MIC: 
      tap: $$mdi:microphone-off$$
      shifted: $$mdi:microsoft-windows$$
      type: sym_by_sym
    SS_WIN:
      tap: $$mdi:monitor-screenshot$$
      hold: $$mdi:microsoft-windows$$
    SSS_WIN:
      tap: $$mdi:monitor-screenshot$$
      shifted: $$mdi:select-drag$$
      hold: $$mdi:microsoft-windows$$
      type: sym_by_sym
    CSR_WIN:
      tap: $$mdi:monitor-screenshot$$
      shifted: $$mdi:video-outline$$
      hold: $$mdi:microsoft-windows$$
      type: sym_by_sym
    COPILOT:
      tap: $$mdi:robot-confused-outline$$
      shifted: $$mdi:microsoft-windows$$
      type: sym_by_sym

    ACUTE: '´'
    DEGREE: '°'
    DEG: '°'
    SECT: '§'
    EURO: '€'
    KP_DIVIDE:
      tap: '/'
      shifted: KP
    KP_MULTIPLY:
      tap: '*'
      shifted: KP
    KP_MINUS:
      tap: '-'
      shifted: KP
    KP_PLUS:
      tap: +
      shifted: KP
    KP_ENTER:
      type: return
      tap: $$mdi:keyboard-return$$
      shifted: KP
    KP_DOT:
      tap: ','
      shifted: KP
    KP_NUM: 'NUML'
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
  zmk_preamble: '#define KEYMAP_DRAWER'
  zmk_additional_includes: ['config']
  zmk_combos:
    combo_oe_colemak: { align: top,    o: 1.25, arc_scale: 0.75 }
    combo_mouse_tog:  { align: bottom, o: 0.5,  arc_scale: 1.0 }